### PR TITLE
Multiregional buckets

### PR DESCRIPTION
**Pull request by hnykda**

### CODE REVIEW

**Comment by lunemec** [comment]
@hnykda I applied the multi_regional storrage class bucket and copied the data, however the bucket permissions do not contain permissions for `allUsers` so they are not public. I also can't find bucket permissions in the terraform, so I guess they were added by hand via google cloud website?

However, I don't see a `public` warning in the current static bucket, so I have not added `allUsers` yet.

Here are changes for website https://github.com/epidemics/covid/pull/378. Upload via GH actions must be also tested.

**Comment by hnykda** [comment]
Ha, I probably _did_ set it manually (I built infra after the release). 

I went to check to GCP where this is set and...

...you are probably going to kill me but I found out that the current one _is_ multi-regional already :facepalm: : 
image

:grimacing: really sorry for the misleading description in the issue, I didn't know that's (likely) default :grimacing:

**Comment by lunemec** [comment]
@hnykda yes, the bucket "storage" is multi-regional, but the storage class is "standard": google docs says this about it:
```
Multi-Regional Storage: Equivalent to Standard Storage, except Multi-Regional Storage can only be used for objects stored in multi-regions or dual-regions.
```

**Comment by hnykda** [comment]
Of course! That's a double fail. :facepalm: Thanks.

**Comment by hnykda** [comment]
OK, back to your original question:
> @hnykda I applied the multi_regional storrage class bucket and copied the data, however the bucket permissions do not contain permissions for allUsers so they are not public. I also can't find bucket permissions in the terraform, so I guess they were added by hand via google cloud website?

I think that the reason for this is that the bucket is not "public" as a bucket itself, but when we load any new files there, they are having `-a public-read` switch making these specific files public. So I guess that's the magic there. Do you think we should set it on the bucket level, if possible?

**Comment by hnykda** [comment]
Other than that I think we can merge.

**Comment by lunemec** [comment]
Yes, I would have the entire bucket public, because I don't think there are files that are not public. And for those I would use different bucket anyway. So we can add it to IAM policy here in terraform, so that this bucket is automatically public.

**Comment by hnykda** [comment]
Sounds good. Could you then set it up as the part of the PR please?

**Comment by hnykda** [comment]
I apologize @lunemec for not making it happen and thank you for your help. right now, it would be finally possible with all the other changes. Nevertheless, given the traffic, it's not worth even the effort.

**Pull request closed without merging**
